import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const html=fs.readFileSync('public/index.html','utf8'),script=fs.readFileSync('public/app.js','utf8');
const wait=()=>new Promise(r=>setTimeout(r,15));
async function mount(initial={}){const dom=new JSDOM(html,{url:'https://side-a.test/',runScripts:'outside-only'}),w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.scrollTo=()=>{};w.AbortSignal=AbortSignal;w.setInterval=()=>0;const state={user:{id:'alice',name:'Alice',platform:'spotify',shareHistory:true},room:null,members:[],shares:[],favorites:[],listens:[],connections:[],available:{spotify:false,apple:false,deezer:false},...initial};let rejectShare=false;const calls=[];w.fetch=async(path,options={})=>{calls.push({path,options});const data=options.body?JSON.parse(options.body):{};let result={ok:true},status=200;if(path==='/api/state')result=structuredClone(state);if(path==='/api/rooms'&&options.method==='POST'){state.room={id:'room-1',name:data.name,owner:'alice'};state.members=[{id:'alice',name:'Alice',platform:'spotify',share_history:0}];}if(path==='/api/shares'){if(rejectShare){status=400;result={error:'Please check the song link.'};}else state.shares.unshift({id:data.requestId,user_id:'alice',name:'Alice',note:data.note,created:Date.now(),track:{...data.track,id:'manual:one',provider:'manual',art:'',album:''}});}if(path==='/api/favorites'){if(options.method==='PUT')state.favorites.push(data.track);else state.favorites=state.favorites.filter(f=>f.id!==data.id);}return new Response(JSON.stringify(result),{status,headers:{'Content-Type':'application/json'}});};w.eval(script);await wait();return {w,state,calls,dom,rejectShares(){rejectShare=true;}};}
test('production onboarding uses Font Awesome, creates real rooms and contains no demo tracks',async()=>{const app=await mount();const {w}=app;assert(w.document.querySelector('#create-room'));assert(!w.document.body.textContent.includes('Jamie'));assert(!w.document.body.textContent.includes('Pink + White'));assert(w.document.querySelector('.fa-house'));w.document.querySelector('#create-room').click();w.document.querySelector('#new-room').value='Two headphones';w.document.querySelector('#create-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait();await wait();assert.equal(w.document.querySelector('#sidebar-room').textContent,'Two headphones');assert(w.document.body.textContent.includes('Your next discovery is waiting'));assert(!w.document.querySelector('#modal').open);app.dom.window.close();});
test('share-song UI writes through API, escapes notes, saves favourites and navigates',async()=>{const app=await mount({room:{id:'r',name:'Our songs',owner:'alice'},members:[{id:'alice',name:'Alice',platform:'spotify'}]});const {w}=app;w.document.querySelector('#share-top').click();w.document.querySelector('#song-title').value='Dreams';w.document.querySelector('#song-artist').value='Fleetwood Mac';w.document.querySelector('#share-note').value='<img src=x onerror=alert(1)>';w.document.querySelector('#share-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait();await wait();assert(w.document.querySelector('.row-copy').textContent.includes('Dreams'));assert(!w.document.querySelector('.row-copy img'));assert(w.document.querySelector('.row-copy').textContent.includes('<img'));w.document.querySelector('[data-save]').click();await wait();await wait();assert.equal(app.state.favorites.length,1);w.document.querySelector('[data-view="saved"]').click();assert(w.document.querySelector('.album-meta h3').textContent.includes('Dreams'));assert.equal(app.calls.filter(c=>c.path==='/api/shares').length,1);app.dom.window.close();});
test('failed submissions preserve user input and unconfigured providers cannot connect',async()=>{const app=await mount({room:{id:'r',name:'Our songs',owner:'alice'},members:[{id:'alice',name:'Alice',platform:'spotify'}]});app.rejectShares();const {w}=app;w.document.querySelector('#share-top').click();w.document.querySelector('#song-title').value='Keep this draft';w.document.querySelector('#song-artist').value='My artist';w.document.querySelector('#share-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait();assert.equal(w.document.querySelector('#song-title').value,'Keep this draft');assert(w.document.querySelector('#form-error').textContent.includes('check'));assert(w.document.querySelector('#modal').open);w.document.querySelector('[data-close]').click();w.document.querySelector('[data-connect]').click();assert([...w.document.querySelectorAll('[data-provider-connect]')].every(b=>b.disabled));app.dom.window.close();});
test('Ressonance branding and motto appear; connections default to sharing with a visible opt-out',async()=>{const app=await mount();const {w}=app;assert(w.document.title.includes('Ressonance'));assert(w.document.body.textContent.includes('different platforms, same frequency'));w.document.querySelector('[data-connect]').click();assert(w.document.querySelector('#connect-sharing').checked);w.document.querySelector('#connect-sharing').click();assert.equal(w.document.querySelector('#connect-sharing').checked,false);app.dom.window.close();});
test('recent listening syncs once on load for connected accounts without a recursive refresh loop',async()=>{const app=await mount({connections:[{provider:'spotify'}],available:{spotify:true,apple:false,deezer:false}});await wait();assert.equal(app.calls.filter(c=>c.path==='/api/sync').length,1);assert.equal(JSON.parse(app.calls.find(c=>c.path==='/api/sync').options.body).provider,'spotify');assert.equal(app.calls.filter(c=>c.path==='/api/state').length,2);app.dom.window.close();});
test('an existing opt-out prevents automatic sync on load',async()=>{const app=await mount({user:{id:'alice',name:'Alice',platform:'spotify',shareHistory:false},connections:[{provider:'spotify'}]});await wait();assert.equal(app.calls.filter(c=>c.path==='/api/sync').length,0);app.dom.window.close();});
