const NOW=()=>Date.now();
const j=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store',...extra}});
class AppError extends Error{constructor(status,message,code='request_failed'){super(message);this.status=status;this.code=code;}}
const fail=(status,message,code)=>{throw new AppError(status,message,code);};
const stmt=(env,sql,...v)=>env.DB.prepare(sql).bind(...v);
const one=(env,sql,...v)=>stmt(env,sql,...v).first();
const all=async(env,sql,...v)=>(await stmt(env,sql,...v).all()).results;
const run=(env,sql,...v)=>stmt(env,sql,...v).run();
const txt=(v,max=120,required=true)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail(400,'Check the required fields and try again.');return v.trim();};
const provider=p=>{if(!['spotify','apple'].includes(p))fail(400,'This music connection is not available.');return p;};
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const bytes=s=>new TextEncoder().encode(s);
const b64url=arr=>btoa(String.fromCharCode(...new Uint8Array(arr))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const hash=async s=>b64url(await crypto.subtle.digest('SHA-256',bytes(s)));
async function key(env){if(!/^[a-f0-9]{64}$/i.test(env.TOKEN_ENCRYPTION_KEY||''))fail(503,'Music connections are awaiting secure setup.','setup_required');return crypto.subtle.importKey('raw',Uint8Array.from(env.TOKEN_ENCRYPTION_KEY.match(/../g),b=>parseInt(b,16)),'AES-GCM',false,['encrypt','decrypt']);}
async function seal(env,value,aad){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:bytes(aad)},await key(env),bytes(JSON.stringify(value)));return JSON.stringify({iv:Array.from(iv),data:btoa(String.fromCharCode(...new Uint8Array(cipher)))});}
async function unseal(env,value,aad){const obj=JSON.parse(value);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(obj.iv),additionalData:bytes(aad)},await key(env),Uint8Array.from(atob(obj.data),c=>c.charCodeAt(0)));return JSON.parse(new TextDecoder().decode(plain));}
function appleReady(env){if(env.APPLE_TEAM_ID&&env.APPLE_KEY_ID&&env.APPLE_PRIVATE_KEY)return true;try{const segment=env.APPLE_MUSIC_DEVELOPER_TOKEN.split('.')[1].replaceAll('-','+').replaceAll('_','/');const d=JSON.parse(atob(segment));return d.exp*1000>NOW()+300000;}catch{return false;}}
let appleTokenCache=null;
async function appleDeveloperToken(env){if(env.APPLE_TEAM_ID&&env.APPLE_KEY_ID&&env.APPLE_PRIVATE_KEY){const fingerprint=await hash(env.APPLE_KEY_ID+env.APPLE_PRIVATE_KEY+env.APP_ORIGIN);if(appleTokenCache?.fingerprint===fingerprint&&appleTokenCache.expires>NOW()+300000)return appleTokenCache.token;const pem=env.APPLE_PRIVATE_KEY.replace(/-----[^-]+-----/g,'').replace(/\s/g,'');let signingKey;try{signingKey=await crypto.subtle.importKey('pkcs8',Uint8Array.from(atob(pem),c=>c.charCodeAt(0)),{name:'ECDSA',namedCurve:'P-256'},false,['sign']);}catch{fail(503,'Apple Music requires a valid signing key.','setup_required');}const issued=Math.floor(NOW()/1000),header=b64url(bytes(JSON.stringify({alg:'ES256',kid:env.APPLE_KEY_ID}))),payload=b64url(bytes(JSON.stringify({iss:env.APPLE_TEAM_ID,iat:issued-30,exp:issued+3600,origin:[env.APP_ORIGIN]})));const unsigned=header+'.'+payload;const signature=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},signingKey,bytes(unsigned));const token=unsigned+'.'+b64url(signature);appleTokenCache={fingerprint,token,expires:(issued+3600)*1000};return token;}if(appleReady(env))return env.APPLE_MUSIC_DEVELOPER_TOKEN;fail(503,'Apple Music is awaiting app-owner setup.','setup_required');}
function availability(env){const secure=/^[a-f0-9]{64}$/i.test(env.TOKEN_ENCRYPTION_KEY||'')&&/^https:\/\//.test(env.APP_ORIGIN||'');return {spotify:secure&&!!env.SPOTIFY_CLIENT_ID,apple:secure&&appleReady(env),deezer:false};}
// Sites headers are trusted only inside the Sites dispatcher. Ordinary Workers
// authenticate with a cryptographically verified Cloudflare Access token.
const accessKeyCache=new Map();
const decodeJWT=segment=>{if(!/^[A-Za-z0-9_-]+$/.test(segment))throw new Error('Invalid JWT');return Uint8Array.from(atob(segment.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));};
function accessIssuer(env){const domain=env.CF_ACCESS_TEAM_DOMAIN||'';if(!/^[a-z0-9][a-z0-9-]*\.cloudflareaccess\.com$/.test(domain)||!env.CF_ACCESS_AUD)fail(503,'Sign-in is awaiting app-owner setup.','setup_required');return 'https://'+domain;}
async function accessKeys(issuer,kid){let entry=accessKeyCache.get(issuer);if(entry&&entry.expires>NOW()&&entry.keys.some(k=>k.kid===kid))return entry.keys;if(entry&&entry.expires>NOW()&&entry.fetched>NOW()-60000)return entry.keys;
 if(!entry?.pending){if(accessKeyCache.size>=8&&!accessKeyCache.has(issuer))accessKeyCache.delete(accessKeyCache.keys().next().value);const pending=(async()=>{const r=await fetch(issuer+'/cdn-cgi/access/certs',{redirect:'error',signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error('Keys unavailable');const d=await r.json();if(!Array.isArray(d.keys)||!d.keys.length||d.keys.length>32)throw new Error('Invalid keys');const value={keys:d.keys,expires:NOW()+600000,fetched:NOW()};accessKeyCache.set(issuer,value);return value.keys;})();entry={...(entry||{}),pending};accessKeyCache.set(issuer,entry);}
 try{return await entry.pending;}catch{accessKeyCache.delete(issuer);fail(503,'Sign-in is temporarily unavailable. Please try again.','auth_unavailable');}}
async function identity(request,env){if(env.AUTH_MODE==='sites'){const id=request.headers.get('oai-authenticated-user-id');if(!id||id.length>250)fail(401,'Sign in to open your music space.','sign_in_required');let name='Music lover';try{const raw=request.headers.get('oai-authenticated-user-full-name');if(raw)name=request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'?decodeURIComponent(raw):raw;}catch{}return {id,name};}
 if(env.AUTH_MODE&&env.AUTH_MODE!=='cloudflare-access')fail(503,'Sign-in is awaiting app-owner setup.','setup_required');const issuer=accessIssuer(env),token=request.headers.get('Cf-Access-Jwt-Assertion');if(!token||token.length>16384)fail(401,'Sign in to open your music space.','sign_in_required');let parts,header,claims,signature;try{parts=token.split('.');if(parts.length!==3)throw 0;header=JSON.parse(new TextDecoder().decode(decodeJWT(parts[0])));claims=JSON.parse(new TextDecoder().decode(decodeJWT(parts[1])));signature=decodeJWT(parts[2]);}catch{fail(401,'Your sign-in has expired. Please sign in again.','sign_in_required');}
 if(!header||typeof header!=='object'||!claims||typeof claims!=='object')fail(401,'Your sign-in has expired. Please sign in again.','sign_in_required');const now=Math.floor(NOW()/1000);if(header.alg!=='RS256'||typeof header.kid!=='string'||header.kid.length>250||header.crit||claims.iss!==issuer||!Array.isArray(claims.aud)||!claims.aud.includes(env.CF_ACCESS_AUD)||!Number.isFinite(claims.exp)||claims.exp<=now||claims.nbf!==undefined&&(!Number.isFinite(claims.nbf)||claims.nbf>now+30)||claims.iat!==undefined&&(!Number.isFinite(claims.iat)||claims.iat>now+30)||typeof claims.sub!=='string'||!claims.sub||claims.sub.length>250||typeof claims.email!=='string'||!claims.email.includes('@')||claims.type==='service')fail(401,'Your sign-in has expired. Please sign in again.','sign_in_required');
 const keys=await accessKeys(issuer,header.kid),jwk=keys.find(k=>k.kid===header.kid&&k.kty==='RSA'&&(!k.alg||k.alg==='RS256')&&(!k.use||k.use==='sig'));let valid=false;try{if(jwk){const publicKey=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);valid=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',publicKey,signature,bytes(parts[0]+'.'+parts[1]));}}catch{}if(!valid)fail(401,'Your sign-in has expired. Please sign in again.','sign_in_required');return {id:'cf:'+await hash(issuer+'|'+claims.sub),name:typeof claims.name==='string'?claims.name.slice(0,60):'Music lover'};}

function originGuard(request,env){const actual=new URL(request.url).origin;const expected=env.APP_ORIGIN||actual;if(actual!==expected)fail(403,'This app is not configured for this address.');if(!['GET','HEAD'].includes(request.method)){if(request.headers.get('Origin')!==expected||request.headers.get('X-SideA-Request')!=='1'||!request.headers.get('Content-Type')?.startsWith('application/json'))fail(403,'Refresh this page and try again.','origin_rejected');}}
async function body(request){if(Number(request.headers.get('Content-Length')||0)>20000)fail(413,'This request is too large.');const reader=request.body?.getReader();if(!reader)return {};const chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>20000){await reader.cancel();fail(413,'This request is too large.');}chunks.push(value);}const combined=new Uint8Array(size);let pos=0;for(const chunk of chunks){combined.set(chunk,pos);pos+=chunk.length;}try{return JSON.parse(new TextDecoder().decode(combined));}catch{fail(400,'This request could not be read.');}}
async function limit(env,id,action,max=50,window=60000){const bucket=Math.floor(NOW()/window);const row=await stmt(env,'INSERT INTO limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',`${id}:${action}:${bucket}`,NOW()+window*2).first();if(row.count>max)fail(429,'Please wait a moment before trying again.','rate_limited');}
async function user(env,id,name){let u=await one(env,'SELECT * FROM users WHERE id=?',id);if(!u){await run(env,'INSERT OR IGNORE INTO users(id,name,created,share_history) VALUES (?,?,?,1)',id,(name||'Music lover').slice(0,60),NOW());u=await one(env,'SELECT * FROM users WHERE id=?',id);}return u;}
async function member(env,id){return one(env,'SELECT r.*,m.joined FROM members m JOIN rooms r ON r.id=m.room_id WHERE m.user_id=?',id);}
async function requireRoom(env,id){const room=await member(env,id);if(!room)fail(409,'Create or join a music space first.','room_required');return room;}
function musicUrl(value){if(!value)return '';try{const u=new URL(value);if(u.protocol!=='https:'||!['open.spotify.com','music.apple.com','www.deezer.com','deezer.com','deezer.page.link'].includes(u.hostname)||u.username||u.password)throw 0;u.hash='';return u.href.slice(0,700);}catch{fail(400,'Use a Spotify, Apple Music or Deezer HTTPS link.');}}
function artwork(value){if(!value)return '';try{const u=new URL(value);if(u.protocol==='https:'&&(u.hostname==='i.scdn.co'||/^[a-z0-9-]+\.mzstatic\.com$/.test(u.hostname)||u.hostname==='cdn-images.dzcdn.net'))return u.href.slice(0,1000);}catch{}return '';}
async function cleanTrack(input){if(!input||typeof input!=='object')fail(400,'Choose a song first.');const title=txt(input.title,160),artist=txt(input.artist,160),url=musicUrl(input.url);let p='manual',pid='';if(['spotify','apple'].includes(input.provider)&&typeof input.providerId==='string'&&/^[a-zA-Z0-9.-]{1,100}$/.test(input.providerId)){p=input.provider;pid=input.providerId;}const id=p==='manual'?'manual:'+await hash(`${title.toLowerCase()}|${artist.toLowerCase()}|${url}`):`${p}:${pid}`;return {id,title,artist,album:typeof input.album==='string'?input.album.slice(0,160):'',url,art:artwork(input.art),provider:p,providerId:pid,isrc:typeof input.isrc==='string'&&/^[A-Z0-9]{12}$/.test(input.isrc)?input.isrc:''};}
function spotifyTrack(t){return {title:t.name,artist:t.artists?.map(a=>a.name).join(', ')||'Unknown artist',album:t.album?.name||'',url:t.external_urls?.spotify||'',art:t.album?.images?.[0]?.url||'',provider:'spotify',providerId:t.id,isrc:t.external_ids?.isrc||''};}
function appleTrack(t){const a=t.attributes||{};return {title:a.name,artist:a.artistName||'Unknown artist',album:a.albumName||'',url:a.url||'',art:a.artwork?.url?.replaceAll('{w}','400').replaceAll('{h}','400')||'',provider:'apple',providerId:t.id,isrc:a.isrc||''};}
async function upstream(url,options={}){let r;try{r=await fetch(url,{...options,signal:AbortSignal.timeout(12000)});}catch{fail(502,'Your music service didn’t respond. Please try again.','provider_unavailable');}if(r.status===429){let detail={};try{detail=await r.json();}catch{}if(detail.reason==='QUOTA_EXCEEDED'||detail.error?.reason==='QUOTA_EXCEEDED')fail(429,'This app has reached its music-service quota. Please try later or contact the app owner.','provider_quota');fail(429,'Your music service is busy. Wait a minute and try again.','provider_rate_limit');}return r;}
async function connected(env,id,p){const c=await one(env,'SELECT * FROM connections WHERE user_id=? AND provider=?',id,p);if(!c)fail(409,'Connect your music account first.','not_connected');return {...c,tokens:await unseal(env,c.encrypted,`${id}:${p}`)};}
async function saveConnection(env,id,p,tokens,expires,shareHistory=true){const queries=[stmt(env,'INSERT INTO connections(user_id,provider,encrypted,expires,updated) VALUES (?,?,?,?,?) ON CONFLICT(user_id,provider) DO UPDATE SET encrypted=excluded.encrypted,expires=excluded.expires,updated=excluded.updated',id,p,await seal(env,tokens,`${id}:${p}`),expires,NOW()),stmt(env,'UPDATE users SET share_history=? WHERE id=?',shareHistory?1:0,id)];if(!shareHistory)queries.push(stmt(env,'DELETE FROM listens WHERE user_id=?',id));await env.DB.batch(queries);}
async function refreshSpotify(env,id,c){const res=await upstream('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:c.tokens.refresh_token,client_id:env.SPOTIFY_CLIENT_ID})});if(!res.ok)fail(409,'Reconnect Spotify to continue.','reconnect');const token=await res.json();if(!token.access_token)fail(502,'Spotify returned an invalid response.');const tokens={...c.tokens,...token,refresh_token:token.refresh_token||c.tokens.refresh_token};await run(env,'UPDATE connections SET encrypted=?,expires=?,updated=? WHERE user_id=? AND provider=? AND encrypted=?',await seal(env,tokens,`${id}:spotify`),NOW()+token.expires_in*1000,NOW(),id,'spotify',c.encrypted);return connected(env,id,'spotify');}
async function musicRequest(env,id,p,path,options={}){if(!availability(env)[p])fail(503,'This music connection needs app-owner configuration.','setup_required');let c=await connected(env,id,p);if(p==='spotify'&&c.expires<NOW()+60000)c=await refreshSpotify(env,id,c);const appleToken=p==='apple'?await appleDeveloperToken(env):null;const send=()=>upstream((p==='spotify'?'https://api.spotify.com/v1':'https://api.music.apple.com/v1')+path,{...options,headers:{'Content-Type':'application/json',...(p==='spotify'?{Authorization:`Bearer ${c.tokens.access_token}`}:{Authorization:`Bearer ${appleToken}`,'Music-User-Token':c.tokens.userToken,Origin:env.APP_ORIGIN})}});let r=await send();if(r.status===401&&p==='spotify'){c=await refreshSpotify(env,id,c);r=await send();}if([401,403].includes(r.status))fail(409,'Your music service denied access. Reconnect your account or check this app’s provider access.','reconnect');if(!r.ok)fail(502,'Your music service could not complete that action.','provider_error');if(r.status===204)return {};const text=await r.text();return text?JSON.parse(text):{};}
async function snapshot(env,id,u){const room=await member(env,id);const connections=await all(env,'SELECT provider,updated,last_sync FROM connections WHERE user_id=?',id);const favorites=await all(env,'SELECT track,created FROM favorites WHERE user_id=? ORDER BY created DESC LIMIT 500',id);const members=room?await all(env,'SELECT u.id,u.name,u.platform,u.share_history,m.joined FROM members m JOIN users u ON u.id=m.user_id WHERE m.room_id=? ORDER BY m.joined',room.id):[];const shares=room?await all(env,'SELECT s.id,s.user_id,s.track,s.note,s.created,u.name FROM shares s JOIN users u ON u.id=s.user_id WHERE s.room_id=? ORDER BY s.created DESC LIMIT 200',room.id):[];const listens=room?await all(env,'SELECT l.track,l.user_id,l.played_at,l.synced_at,u.name FROM listens l JOIN members m ON m.user_id=l.user_id JOIN users u ON u.id=l.user_id WHERE m.room_id=? AND u.share_history=1 AND l.synced_at>? ORDER BY COALESCE(l.played_at,l.synced_at) DESC LIMIT 60',room.id,NOW()-7*86400000):[];return {user:{id:u.id,name:u.name,platform:u.platform,shareHistory:!!u.share_history},room,members,shares:shares.map(s=>({...s,track:JSON.parse(s.track)})),favorites:favorites.map(f=>({...JSON.parse(f.track),savedAt:f.created})),listens:listens.map(l=>({...l,track:JSON.parse(l.track)})),connections,available:availability(env)};}
async function handleApi(request,env,ctx){
const url=new URL(request.url),path=url.pathname,method=request.method;
if(!env.DB)fail(503,'Your music space is temporarily unavailable. Please try again.');
originGuard(request,env);const principal=await identity(request,env),id=principal.id;const u=await user(env,id,principal.name);
if(method!=='GET')await limit(env,id,'writes',60);
if(path==='/api/state'&&method==='GET'){await limit(env,id,'reads',150);await env.DB.batch([stmt(env,'DELETE FROM limits WHERE key IN (SELECT key FROM limits WHERE expires<? LIMIT 200)',NOW()),stmt(env,'DELETE FROM listens WHERE (user_id,track_key) IN (SELECT user_id,track_key FROM listens WHERE synced_at<? LIMIT 200)',NOW()-7*86400000),stmt(env,'DELETE FROM invites WHERE hash IN (SELECT hash FROM invites WHERE expires<? LIMIT 100)',NOW()),stmt(env,'DELETE FROM oauth WHERE hash IN (SELECT hash FROM oauth WHERE expires<? LIMIT 100)',NOW())]);return j(await snapshot(env,id,u));}
if(path==='/api/profile'&&method==='PATCH'){const b=await body(request);const name=txt(b.name,60);if(!['spotify','apple','deezer'].includes(b.platform)||typeof b.shareHistory!=='boolean')fail(400,'Choose your music and sharing preferences.');const queries=[stmt(env,'UPDATE users SET name=?,platform=?,share_history=? WHERE id=?',name,b.platform,b.shareHistory?1:0,id)];if(!b.shareHistory)queries.push(stmt(env,'DELETE FROM listens WHERE user_id=?',id));await env.DB.batch(queries);return j({ok:true});}
if(path==='/api/rooms'&&method==='POST'){if(await member(env,id))fail(409,'Leave your current space before creating another.');const b=await body(request),name=txt(b.name,80),rid=crypto.randomUUID();await env.DB.batch([stmt(env,'INSERT INTO rooms(id,name,owner,created) VALUES (?,?,?,?)',rid,name,id,NOW()),stmt(env,'INSERT INTO members(user_id,room_id,joined) VALUES (?,?,?)',id,rid,NOW())]);return j({id:rid},201);}
if(path==='/api/rooms'&&method==='PATCH'){const room=await requireRoom(env,id);if(room.owner!==id)fail(403,'Only the space owner can rename it.');const b=await body(request);await run(env,'UPDATE rooms SET name=? WHERE id=?',txt(b.name,80),room.id);return j({ok:true});}
if(path==='/api/invites'&&method==='POST'){const room=await requireRoom(env,id);if(room.owner!==id)fail(403,'Only the space owner can create invitations.');await limit(env,id,'invites',10,3600000);const token=random(),expires=NOW()+7*86400000;await env.DB.batch([stmt(env,'DELETE FROM invites WHERE room_id=?',room.id),stmt(env,'INSERT INTO invites(hash,room_id,expires) VALUES (?,?,?)',await hash(token),room.id,expires)]);return j({token,expires});}
if(path==='/api/invites'&&method==='DELETE'){const room=await requireRoom(env,id);if(room.owner!==id)fail(403,'Only the space owner can revoke invitations.');await run(env,'DELETE FROM invites WHERE room_id=?',room.id);return j({ok:true});}
if(path==='/api/join'&&method==='POST'){await limit(env,id,'join',10,3600000);if(await member(env,id))fail(409,'Leave your current space before joining another.');const b=await body(request),token=txt(b.token,64);if(!/^[a-f0-9]{64}$/.test(token))fail(400,'This invite link is invalid.');const h=await hash(token);const q=await env.DB.batch([stmt(env,'INSERT INTO members(user_id,room_id,joined) SELECT ?,room_id,? FROM invites WHERE hash=? AND expires>? AND (SELECT COUNT(*) FROM members WHERE room_id=invites.room_id)<20',id,NOW(),h,NOW()),stmt(env,'DELETE FROM invites WHERE hash=? AND EXISTS (SELECT 1 FROM members WHERE user_id=? AND room_id=invites.room_id)',h,id)]);if(!q[0].meta.changes)fail(410,'This invitation has expired, was used, or the space is full.');return j({ok:true});}
if(path==='/api/rooms/leave'&&method==='POST'){const room=await requireRoom(env,id);if(room.owner===id)fail(409,'As the owner, delete the space in settings instead of leaving.');await env.DB.batch([stmt(env,'DELETE FROM shares WHERE user_id=? AND room_id=?',id,room.id),stmt(env,'DELETE FROM members WHERE user_id=?',id)]);return j({ok:true});}
if(path==='/api/rooms'&&method==='DELETE'){const room=await requireRoom(env,id);if(room.owner!==id)fail(403,'Only the owner can delete this space.');await run(env,'DELETE FROM rooms WHERE id=?',room.id);return j({ok:true});}
if(path==='/api/shares'&&method==='POST'){const room=await requireRoom(env,id),b=await body(request),t=await cleanTrack(b.track),note=txt(b.note||'',280,false);if(!/^[a-f0-9-]{36}$/.test(b.requestId||''))fail(400,'Refresh the page and try sharing again.');await run(env,'INSERT OR IGNORE INTO shares(id,room_id,user_id,track,note,created) VALUES (?,?,?,?,?,?)',b.requestId,room.id,id,JSON.stringify(t),note,NOW());return j({ok:true},201);}
if(path.startsWith('/api/shares/')&&method==='DELETE'){const room=await requireRoom(env,id);await run(env,'DELETE FROM shares WHERE id=? AND room_id=? AND (user_id=? OR ?=?)',path.split('/').at(-1),room.id,id,room.owner,id);return j({ok:true});}
if(path==='/api/favorites'&&method==='PUT'){const b=await body(request),t=await cleanTrack(b.track);const count=await one(env,'SELECT count(*) as n FROM favorites WHERE user_id=?',id);if(count.n>=500&&!await one(env,'SELECT 1 FROM favorites WHERE user_id=? AND track_key=?',id,t.id))fail(409,'Your collection is full. Remove a favourite first.');await run(env,'INSERT OR IGNORE INTO favorites(user_id,track_key,track,created) VALUES (?,?,?,?)',id,t.id,JSON.stringify(t),NOW());return j({ok:true});}
if(path==='/api/favorites'&&method==='DELETE'){const b=await body(request);await run(env,'DELETE FROM favorites WHERE user_id=? AND track_key=?',id,txt(b.id,150));return j({ok:true});}
if(path==='/api/history'&&method==='DELETE'){await run(env,'DELETE FROM listens WHERE user_id=?',id);return j({ok:true});}
if(path==='/api/connections/spotify/start'&&method==='POST'){if(!availability(env).spotify)fail(503,'Spotify is awaiting app-owner setup. You can still share Spotify song links.','setup_required');await limit(env,id,'oauth',10,3600000);const preferences=await body(request);const state=random(),verifier=random();await env.DB.batch([stmt(env,'DELETE FROM oauth WHERE expires<? OR user_id=?',NOW(),id),stmt(env,'INSERT INTO oauth(hash,user_id,verifier,expires) VALUES (?,?,?,?)',await hash(state),id,await seal(env,{verifier,shareHistory:preferences.shareHistory!==false},id+':oauth'),NOW()+600000)]);const auth=new URL('https://accounts.spotify.com/authorize');auth.search=new URLSearchParams({response_type:'code',client_id:env.SPOTIFY_CLIENT_ID,redirect_uri:env.APP_ORIGIN+'/api/oauth/spotify/callback',scope:'user-read-recently-played user-library-modify',state,code_challenge_method:'S256',code_challenge:await hash(verifier)});return j({url:auth.href},200,{'Set-Cookie':`sa_oauth=${state}; Path=/api/oauth/spotify; HttpOnly; Secure; SameSite=Lax; Max-Age=600`});}
if(path==='/api/oauth/spotify/callback'&&method==='GET'){const state=url.searchParams.get('state')||'',cookie=request.headers.get('Cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('sa_oauth='))?.slice(9);if(!/^[a-f0-9]{64}$/.test(state)||cookie!==state)fail(400,'This Spotify connection request expired. Please try again.');const row=await stmt(env,'DELETE FROM oauth WHERE hash=? AND user_id=? AND expires>? RETURNING verifier',await hash(state),id,NOW()).first();if(!row)fail(400,'This Spotify connection request expired. Please try again.');let destination='/?connection=cancelled';if(!url.searchParams.has('error')){const code=url.searchParams.get('code');if(!code)fail(400,'Spotify did not return an authorization code.');const {verifier,shareHistory}=await unseal(env,row.verifier,id+':oauth');const r=await upstream('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:env.SPOTIFY_CLIENT_ID,code,redirect_uri:env.APP_ORIGIN+'/api/oauth/spotify/callback',code_verifier:verifier})});if(!r.ok)fail(502,'Spotify authorization failed. Please connect again.');const t=await r.json();if(!t.access_token||!t.refresh_token)fail(502,'Spotify did not return the required authorization.');await saveConnection(env,id,'spotify',t,NOW()+t.expires_in*1000,shareHistory!==false);destination='/?connection=spotify';}return new Response(null,{status:303,headers:{Location:destination,'Cache-Control':'no-store','Set-Cookie':'sa_oauth=; Path=/api/oauth/spotify; Secure; HttpOnly; SameSite=Lax; Max-Age=0'}});}
if(path==='/api/apple/config'&&method==='GET'){if(!availability(env).apple)fail(503,'Apple Music is awaiting app-owner setup.','setup_required');return j({developerToken:await appleDeveloperToken(env)});}
if(path==='/api/connections/apple'&&method==='POST'){if(!availability(env).apple)fail(503,'Apple Music is awaiting app-owner setup.','setup_required');const b=await body(request),token=txt(b.musicUserToken,5000);const r=await upstream('https://api.music.apple.com/v1/me/storefront',{headers:{Authorization:`Bearer ${await appleDeveloperToken(env)}`,'Music-User-Token':token,Origin:env.APP_ORIGIN}});if(!r.ok)fail(409,'Apple Music authorization failed. Try connecting again.');const d=await r.json(),storefront=d.data?.[0]?.id;if(!/^[a-z]{2}$/.test(storefront||''))fail(502,'Apple Music did not return your region.');await saveConnection(env,id,'apple',{userToken:token,storefront},0,b.shareHistory!==false);return j({ok:true});}
if(path.startsWith('/api/connections/')&&method==='DELETE'){const p=provider(path.split('/').at(-1));await env.DB.batch([stmt(env,'DELETE FROM connections WHERE user_id=? AND provider=?',id,p),stmt(env,'DELETE FROM listens WHERE user_id=? AND provider=?',id,p)]);return j({ok:true});}
if(path==='/api/sync'&&method==='POST'){const b=await body(request),p=provider(b.provider);if(!u.share_history)fail(409,'Enable listening sharing in your profile before syncing.','sharing_disabled');await limit(env,id,'sync:'+p,1,30000);const d=await musicRequest(env,id,p,p==='spotify'?'/me/player/recently-played?limit=30':'/me/recent/played/tracks?types=songs&limit=30');const rows=p==='spotify'?(d.items||[]).filter(i=>i.track?.id).map(i=>({track:spotifyTrack(i.track),playedAt:Date.parse(i.played_at)||null})):(d.data||[]).filter(i=>i.type==='songs').map(i=>({track:appleTrack(i),playedAt:null}));const queries=[stmt(env,'DELETE FROM listens WHERE user_id=? AND provider=?',id,p)];for(const row of rows.slice(0,30)){if(row.playedAt&&row.playedAt<NOW()-7*86400000)continue;const t=await cleanTrack(row.track);queries.push(stmt(env,'INSERT INTO listens(user_id,track_key,provider,track,played_at,synced_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM users WHERE id=? AND share_history=1) AND EXISTS(SELECT 1 FROM connections WHERE user_id=? AND provider=?) ON CONFLICT(user_id,track_key) DO UPDATE SET played_at=MAX(COALESCE(listens.played_at,0),COALESCE(excluded.played_at,0)),synced_at=excluded.synced_at',id,t.id,p,JSON.stringify(t),row.playedAt,NOW(),id,id,p));}queries.push(stmt(env,'UPDATE connections SET last_sync=? WHERE user_id=? AND provider=?',NOW(),id,p));await env.DB.batch(queries);return j({ok:true,count:rows.length});}
if(path==='/api/search'&&method==='GET'){await limit(env,id,'search',20);const p=provider(url.searchParams.get('provider')),q=txt(url.searchParams.get('q'),200);let d;if(p==='spotify')d=await musicRequest(env,id,p,'/search?type=track&limit=5&q='+encodeURIComponent(q));else{const c=await connected(env,id,p);d=await musicRequest(env,id,p,`/catalog/${c.tokens.storefront}/search?types=songs&limit=5&term=${encodeURIComponent(q)}`);}const results=p==='spotify'?(d.tracks?.items||[]).map(spotifyTrack):(d.results?.songs?.data||[]).map(appleTrack);return j({tracks:await Promise.all(results.map(cleanTrack))});}
if(path==='/api/library'&&method==='POST'){await limit(env,id,'library',20);const b=await body(request),p=provider(b.provider),pid=txt(b.providerId,100);if(p==='spotify'&&!/^[a-zA-Z0-9]{22}$/.test(pid)||p==='apple'&&!/^\d+$/.test(pid))fail(400,'Choose a valid track from this provider.');await musicRequest(env,id,p,p==='spotify'?'/me/library?uris='+encodeURIComponent('spotify:track:'+pid):'/me/library?ids%5Bsongs%5D='+encodeURIComponent(pid),{method:p==='spotify'?'PUT':'POST'});return j({ok:true,status:p==='apple'?'accepted':'saved'});}
if(path==='/api/export'&&method==='GET'){const data=await snapshot(env,id,u);return j({exportedAt:new Date().toISOString(),profile:data.user,favorites:data.favorites,shares:data.shares.filter(s=>s.user_id===id),listens:data.listens.filter(l=>l.user_id===id),connections:data.connections},200,{'Content-Disposition':'attachment; filename="ressonance-data.json"'});}
if(path==='/api/account'&&method==='DELETE'){await env.DB.batch([stmt(env,'DELETE FROM users WHERE id=?',id),stmt(env,'DELETE FROM limits WHERE substr(key,1,?)=?',id.length+1,id+':')]);return j({ok:true});}
fail(404,'This action could not be found.');
}
function security(response){const h=new Headers(response.headers);h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','no-referrer');h.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');h.set('Content-Security-Policy',"default-src 'self'; script-src 'self' https://js-cdn.music.apple.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://i.scdn.co https://*.mzstatic.com https://cdn-images.dzcdn.net; font-src 'self'; connect-src 'self' https://*.music.apple.com https://*.itunes.apple.com https://*.apple.com; frame-src https://*.apple.com https://*.music.apple.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com;");return new Response(response.body,{status:response.status,headers:h});}
export default {async fetch(request,env,ctx){let response;try{const url=new URL(request.url);if(url.pathname==='/api/login'&&request.method==='GET'){let target=url.searchParams.get('return_to')||'/';if(!/^\/(?!\/)/.test(target)||target.length>2000||/[\u0000-\u0020\u007f\\]/.test(target))target='/';const login=env.AUTH_MODE==='sites'?'/signin-with-chatgpt?return_to='+encodeURIComponent(target):target;response=new Response(null,{status:303,headers:{Location:login,'Cache-Control':'no-store'}});}else if(url.pathname.startsWith('/api/'))response=await handleApi(request,env,ctx);else if(['GET','HEAD'].includes(request.method)){const path=url.pathname==='/'?'/index.html':url.pathname;const file=ASSETS[path];if(file){response=new Response(request.method==='HEAD'?null:Uint8Array.from(atob(file.body),c=>c.charCodeAt(0)),{headers:{'Content-Type':file.type,'Cache-Control':path.endsWith('.woff2')?'public, max-age=31536000, immutable':'no-cache'}});}else response=j({error:'Page not found.'},404);}else response=j({error:'Method not allowed.'},405);}catch(e){const status=e instanceof AppError?e.status:503;if(!(e instanceof AppError))console.error('side-a.request_failed',{type:e.name});response=j({error:e instanceof AppError?e.message:'Your music space is temporarily unavailable. Please try again.',code:e instanceof AppError?e.code:'unavailable'},status);}if(new URL(request.url).pathname==='/api/oauth/spotify/callback'&&response.status>=400){let detail;try{detail=await response.clone().json();}catch{}response=new Response(null,{status:303,headers:{Location:'/?connection_error='+encodeURIComponent(detail?.error||'Connection failed. Please try again.'),'Cache-Control':'no-store','Set-Cookie':'sa_oauth=; Path=/api/oauth/spotify; Secure; HttpOnly; SameSite=Lax; Max-Age=0'}});}return security(response);}};
